// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySfJk5w64HMyS3QChk8G6dL5kRvPAgDc',
    appId: '1:1060165579239:web:6c4b4c9b33afe2615c8d42',
    messagingSenderId: '1060165579239',
    projectId: 'elemam-79dd8',
    authDomain: 'elemam-79dd8.firebaseapp.com',
    storageBucket: 'elemam-79dd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyf-gdWvjUEtCO_FfnH2SVqSJXRZPkJJo',
    appId: '1:1060165579239:android:803c25493da4b5085c8d42',
    messagingSenderId: '1060165579239',
    projectId: 'elemam-79dd8',
    storageBucket: 'elemam-79dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs68MKZNf83Q3uKFav-uy1wpam98HEY4g',
    appId: '1:1060165579239:ios:33fcb4a39099ec125c8d42',
    messagingSenderId: '1060165579239',
    projectId: 'elemam-79dd8',
    storageBucket: 'elemam-79dd8.firebasestorage.app',
    iosBundleId: 'com.webinar.webinar',
  );
}
